const quotes: Array<string> = [
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Life is what happens when you're busy making other plans. - John Lennon",
  "In the end, it's not the years in your life that count. It's the life in your years. - Abraham Lincoln",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "You miss 100% of the shots you don't take. - Wayne Gretzky",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
  "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
  "Life is a journey that must be traveled no matter how bad the roads and accommodations. - Oliver Goldsmith",
  "Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman",
  "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost",
  "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
  "You become what you believe. - Oprah Winfrey",
  "Dream big and dare to fail. - Norman Vaughan",
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
  "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
  "Happiness is not something ready made. It comes from your own actions. - Dalai Lama",
  "The best way to predict the future is to create it. - Peter Drucker",
  "In the middle of difficulty lies opportunity. - Albert Einstein",
  "Life is really simple, but we insist on making it complicated. - Confucius",
  "Everything you can imagine is real. - Pablo Picasso",
  "Turn your wounds into wisdom. - Oprah Winfrey",
  "Don't count the days, make the days count. - Muhammad Ali",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "The only person you should try to be better than is the person you were yesterday. - Anonymous",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "The purpose of our lives is to be happy. - Dalai Lama",
  "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
  "You must be the change you wish to see in the world. - Mahatma Gandhi",
  "With the new day comes new strength and new thoughts. - Eleanor Roosevelt",
  "Strive not to be a success, but rather to be of value. - Albert Einstein",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "It always seems impossible until it is done. - Nelson Mandela",
  "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment. - Buddha",
  "Life is what happens when you're busy making other plans. - John Lennon",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
  "When something is important enough, you do it even if the odds are not in your favor. - Elon Musk",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "Change your thoughts and you change your world. - Norman Vincent Peale",
  "The best way to predict the future is to invent it. - Alan Kay",
  "I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "Life is really simple, but we insist on making it complicated. - Confucius",
  "Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson",
  "You miss 100% of the shots you don't take. - Wayne Gretzky",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "You can't use up creativity. The more you use, the more you have. - Maya Angelou",
  "Happiness is not something ready-made. It comes from your own actions. - Dalai Lama",
  "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
  "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "You become what you believe. - Oprah Winfrey",
  "Dream big and dare to fail. - Norman Vaughan",
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
  "With the new day comes new strength and new thoughts. - Eleanor Roosevelt",
  "Turn your wounds into wisdom. - Oprah Winfrey",
  "Life is what happens to you while you're busy making other plans. - John Lennon",
  "The purpose of our lives is to be happy. - Dalai Lama",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
  "Life is a journey that must be traveled no matter how bad the roads and accommodations. - Oliver Goldsmith",
  "The best way to predict the future is to create it. - Peter Drucker",
  "In the middle of difficulty lies opportunity. - Albert Einstein",
  "Everything you can imagine is real. - Pablo Picasso",
  "It always seems impossible until it is done. - Nelson Mandela",
  "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment. - Buddha",
  "Life is really simple, but we insist on making it complicated. - Confucius",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison",
  "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "It always seems impossible until it's done. - Nelson Mandela",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Do not go where the path may lead, go instead where there is no path and leave",
];

export default quotes;
